name: Format Fix
on:
  push:
    branches:
      - main
  workflow_dispatch:
concurrency:
  # Skip intermediate builds: all builds except for builds on the `main` branch
  # Cancel intermediate builds: only pull request builds
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/main' || github.run_number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
permissions:
  contents: write
  pull-requests: write
jobs:
  fix:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: julia-actions/setup-julia@f6f565d9f7cf12f53dc8045742460d6260ad3b39 # v3.0.1
        with:
          version: '1'
      - run: make format-fix
      - name: Create pull request
        id: create_pr
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{  secrets.GITHUB_TOKEN }}
          commit-message: '🤖 Automatically format the source code files'
          title: '🤖 Automatically format the source code files'
          body: |-
            This pull request formats the source code files using the JuliaFormatter package.
            
            Note: CI will not automatically run on this PR. Please open and close this PR to trigger CI.
          branch: bot/format/${{ github.ref }}
          delete-branch: true
